# -*- coding: utf-8 -*-
"""Yeşil ve Mavi Renk Tespiti.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w1Fdj1QA-gHeCGu4vu5sRE1UsZ-IHCoR
"""

import cv2
import numpy as np
cap = cv2.VideoCapture(0)

while True:
  _,frame = cap.read()
  hsv_frame = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)

  #mavi renk tespiti

  low_blue = np.array([94,80,2])
  high_blue = np.array([126,255,255])
  blue_mask = cv2.inRange(hsv_frame,low_blue,high_blue)
  blue = cv2.bitwise_and(frame,frame,mask=blue_mask)
#yeşil tespiti
  low_green=np.array([25,52,72])
  high_green = np.array([102,255,255])
  green_mask = cv2.inRange(hsv_frame,low_green,high_green)
  green = cv2.bitwise_and(frame,frame,mask = green_mask)

  low = np.array([0,42,0])
  high= np.array([179,255,255])
  mask = cv2.inRange(hsv_frame,low,high)
  result = cv2.bitwise_and(frame,frame,mask = mask)
  cv2.imshow("Frame",frame)
  cv2.imshow("Blue",blue)
  cv2.imshow("Green",green)
  cv2.imshow("Result",result)
  key = cv2.waitKey(1)
  if key == 27:
    break